config/routes.rb
Rails.application.routes.draw do
  root 'application#index'

  resources :companies, only: [:index]
  resources :invitations, only: [:create]
  resources :forms, param: :form_type, only: [:show, :create]

  namespace :api do
    post "ruby_sg_bot/webhook", to: "ruby_sg_bot#webhook"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < FrozenRecord::Base
  scope :sorted, -> { all.order(updated_on: :desc, name: :asc, contribution_count: :desc) }

  def supporter?
    contribution_count.to_i >= 1
  end

  def self.supporters
    sorted
      .select(&:supporter?)
      .sort_by do |company|
        [
          Date.today - Date.strptime(company.updated_on, "%Y-%m-%d"),
        ]
      end
  end

  def self.non_supporters
    sorted
      .reject(&:supporter?)
  end
end

app/models/form_response.rb
class FormResponse < ApplicationRecord
  validates :form_type, presence: true
  validates :response, presence: true
end

app/models/invitation.rb
class Invitation
  include ActiveModel::Model
  include ActiveModel::Validations

  include HTTParty
  base_uri "https://#{ENV['SLACK_TEAM']}.slack.com"

  attr_accessor :email

  validates_presence_of :email

  def create_and_send
    return unless valid?

    options = {
      body: {
        email:      @email,
        channels:   ENV['SLACK_CHANNELS'],
        token:      ENV['SLACK_TOKEN'],
        set_active: 'true',
        _attempts:  1
      }
    }

    response = self.class.post("/api/users.admin.invite?t=#{Time.now.to_i}", options)
    if response['ok']
      true
    else
      errors.add(:email, "Slack Error: #{response['error']}")
      false
    end
  end
end

app/models/ruby_sg_bot_subscriber.rb
class RubySgBotSubscriber < ApplicationRecord
  validates :chat_id, presence: true
end

app/controllers/api/application_controller.rb
module Api
  class ApplicationController < ActionController::API
  end
end

app/controllers/api/ruby_sg_bot_controller.rb
class Api::RubySgBotController < Api::ApplicationController
  def webhook
    # Telegram's update webhook sends multiple types of message. For now, this
    # app only uses the :message type event. For the full API reference, see
    # https://core.telegram.org/bots/api#update
    return head :no_content unless params.has_key?(:message)

    if ruby_sg_bot_joined_group? && RubySgBotSubscriber.find_or_create_by(chat_id: tg_chat_id.to_s)
      message = <<~TELEGRAM_MESSAGE
      👋 At your service!
      TELEGRAM_MESSAGE

      ::Telegram.bot.send_message(
        chat_id: tg_chat_id,
        text: message,
        parse_mode: :Markdown,
        disable_web_page_preview: true
      )
    elsif ruby_sg_bot_left_group?
      RubySgBotSubscriber.find_by(chat_id: tg_chat_id.to_s)&.destroy
    end

    head :no_content
  end

  private

  def rubysg_bot_id
    ENV["RUBY_SG_BOT_ID"]
  end

  def ruby_sg_bot_joined_group?
    (tg_object[:chat][:type] == "group" || tg_object[:chat][:type] == "supergroup") &&
      tg_object[:new_chat_member] &&
      tg_object[:new_chat_member][:id].to_s == rubysg_bot_id
  end

  def ruby_sg_bot_left_group?
    (tg_object[:chat][:type] == "group" || tg_object[:chat][:type] == "supergroup") &&
      tg_object[:left_chat_member] &&
      tg_object[:left_chat_member][:id].to_s == rubysg_bot_id
  end

  def tg_chat_id
    tg_object[:chat][:id]
  end

  def tg_object
    @tg_object ||= params
      .require(:message)
      .permit(
        chat: [:id, :type],
        new_chat_member: [:id],
        left_chat_member: [:id]
      )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
    @supporter_companies = Company.supporters.first(8)
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @supporter_companies = Company.supporters
    @other_companies = Company.non_supporters
  end
end

app/controllers/forms_controller.rb
# frozen_string_literal: true

class FormsController < ApplicationController
  def show
    @form = find_form_klass(params[:form_type]).new

  rescue NameError
    redirect_to "/404"
  end

  def create
    @form = find_form_klass(form_params.require(:form_type)).new(form_params)

    if @form.submit
      redirect_to :root
    else
      render :show
    end

  rescue NameError
    redirect_to "/404"
  end

  private

  def form_params
    params.require(:form)
  end

  def find_form_klass(form_type)
    "Feedback::#{form_type.camelcase}".constantize
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  def create
    invitation = Invitation.new(model_param)

    if invitation.create_and_send
      redirect_to root_path, notice: 'We have successfully invited you to Slack. See you there!'
    else
      redirect_to root_path, alert:  "Sorry, we were not able to invite you to Slack - #{invitation.errors.full_messages}."
    end
  end

  private

    def model_param
      params.require(:invitation).permit(:email)
    end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def rubysg_telegram_qr_code_svg
    RQRCode::QRCode
      .new(rubysg_telegram_link)
      .as_svg(
        offset: 10,
        color: '222529',
        shape_rendering: 'crispEdges',
        module_size: 6,
        standalone: true
      ).html_safe
  end

  def rubysg_telegram_link
    "https://t.me/+2SjusiYG07pjYWE1"
  end

  def rubysg_meetup_com_link
    "http://www.meetup.com/Singapore-Ruby-Group"
  end

  def rubysg_engineerssg_link
    "https://engineers.sg/organization/rubysg--57"
  end

  def rubysg_github_guide_link
    "https://github.com/rubysg/singapore"
  end

  def rubysg_photo_album_link
    "https://www.icloud.com/sharedalbum/#B0SJtdOXmmrrha"
  end
end

app/views/application/index.html.slim
.section
  .container-md.col-md-7
    h2.section-heading.heading-with-line.ms-3 Every 1st Wednesday of the Month
    p We hold meetups with speakers giving talks about Ruby and share 5 random Ruby tips. Building & shipping is how we roll. It's a great way to meet Ruby enthusiasts!
    p
      a.btn.btn-custom.me-2.mb-2[href=rubysg_meetup_com_link target='_blank']
        span Come join us!
      a.btn.btn-custom.btn-custom-success.me-2.mb-2[href=rubysg_engineerssg_link target='_blank']
        span Recordings
      a.btn.btn-custom.btn-custom-success.me-2.mb-2[href=rubysg_photo_album_link target='_blank']
        span Photos

.section.section-blue
  .container-md.col-md-7
    h2.section-heading-center
      ' Chat with us on
      = icon('fab', 'telegram')
    p.text-center.qr-code
      = rubysg_telegram_qr_code_svg
    p.text-center
      a.btn.btn-custom[href=rubysg_telegram_link target='_blank']
        span Join Telegram

.section
  .container-md.col-md-7
    h3.section-heading.heading-with-line.ms-3  Looking for Ruby jobs?

    p These Singapore companies use Ruby and they may be hiring.

    .ruby-companies
      - @supporter_companies.each do |company|
        = link_to company.website, target: '_blank', class: 'ruby-company' do
          img.company-logo[src=company.logo_url]
    p.text-center
      = link_to 'See more', companies_path, class: 'btn btn-custom'

.section.section-gray
  .container-md.col-md-7
    h3.section-heading-center.heading-with-line Visiting Singapore?
    p.mx-md-5.px-md-5.text-center
      = image_tag('skyline.png', class: 'img-fluid')
      ' We have prepared a guide for visiting Rubyists. Check out #{link_to 'the guide on GitHub', rubysg_github_guide_link} and feel free to reach out to us!

app/views/companies/_company.html.slim
.col-lg-6.col-md-12
  .company.p-4.m-2.d-flex.align-items-center
    - if company.hiring_url.present?
      = link_to company.hiring_url, class: 'company-hiring', target: '_blank'
        i.fa.fa-2x.fa-briefcase.hiring-icon
    .company-brand.me-4
      = link_to company.website, target: '_blank' do
        div.company-logo[style='background-image: url(#{company.logo_url})']
    .company-description
      h5.fw-lighter.company-name.mb-2.text-break
        = company.name
      .company-address.text-break
        = company.address
      .contact.text-muted.text-break
        = company.email

app/views/companies/index.html.slim
.section
  .container
    h2.section-heading.section-heading-center Our Community Supporters! Thank you! #{icon :fas, :heart}
    p.text-center These companies have recently sponsored RubySG meetups and/or provided speakers
    .row
      = render @supporter_companies, partial: 'company'

.section
  .container
    h2.section-heading More Companies Using Ruby
    .row
      = render @other_companies, partial: 'company'

.section
  .container
    p.text-center
      ' More Ruby jobs in Singapore
      a[href="https://www.nodeflair.com/jobs?query=&page=1&tech_stacks%5B%5D=Ruby" target="_blank"] here
      ' !

app/views/forms/show.html.slim
.container
  .section
    h1 = @form.title

    = form_with(id: :form, model: @form) do |form|
      = form.hidden_field :form_type, value: @form.form_type

      - @form.questions.each do |question|
        - if question[:options].is_a?(Array)
          = field_set_tag nil, "cf-questions" => question[:question] do
            - question[:options].each do |option|
              = form.radio_button question[:key], option, required: question[:required], "cf-label" => option

        - else
          = form.text_field question[:key], required: question[:required], "cf-questions" => question[:question]

    div[id="cf-context" role="cf-context" cf-context=true]

script[type="text/javascript" src="https://cdn.jsdelivr.net/gh/space10-community/conversational-form@1.0.1/dist/conversational-form.min.js" crossorigin=true]

css:
  /*
    TODO: Move this into asset pipeline. For some reason putting styles in
      base.scss does not get picked up.
  */
  html {
    scroll-behavior: smooth;
  }

  #cf-context {
    width: 100%;
    height: 500px;
  }

  #form {
    position: absolute;
    height: 0px;
    visibility: hidden;
  }

javascript:
  var conversationalForm = window.cf.ConversationalForm.startTheConversation({
    formEl: document.getElementById("form"),
    context: document.getElementById("cf-context"),
    theme: 'red'
  })

app/views/layouts/application.html.slim
doctype html
html
  head
    title Ruby Singapore
    meta name='description' content='Hello! We are the Ruby community in Singapore! Join us at our next Monthly meetup or RailsGirls event.'
    meta name='viewport' content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no'
    meta property='og:title' content='Ruby Singapore'
    meta property='og:type' content='website'
    meta property='og:image:url' content='http://www.ruby.sg/rubysg-banner.png'
    meta property='og:image:alt' content='RubySG Banner'
    meta property='og:image:width' content='1200'
    meta property='og:image:height' content='640'

    link href='https://fonts.googleapis.com/css?family=Poppins:400,500,700' rel='stylesheet' type='text/css'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = favicon_link_tag       'favicon.ico'
    = csrf_meta_tags
  body
    / <a href="https://github.com/rubysg/rubysg-reboot" class="github-corner"><svg width="80" height="80" viewBox="0 0 250 250" style="fill:#fff; color:#eg233c; position: absolute; top: 0; border: 0; right: 0;"><path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path><path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path><path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" fill="currentColor" class="octo-body"></path></svg></a><style>.github-corner:hover .octo-arm{animation:octocat-wave 560ms ease-in-out}@keyframes octocat-wave{0%,100%{transform:rotate(0)}20%,60%{transform:rotate(-25deg)}40%,80%{transform:rotate(10deg)}}@media (max-width:500px){.github-corner:hover .octo-arm{animation:none}.github-corner .octo-arm{animation:octocat-wave 560ms ease-in-out}}</style>

    .banner
      .container-fluid.py-5.text-white
        = link_to root_path do
          h1.title.py-md-4
            = image_tag('ruby-sg-logo.png', class: 'logo me-3')
            ' RubySG
        p Hello! We are the Ruby community in Singapore!

    .content
      .text-center
        = flash_messages
      = yield
    footer
      .container-fluid.d-flex.justify-content-between
        span &copy; RubySG #{Time.current.year}
        span.text-end Made with #{icon :fas, :heart} by RubySG